version: "3.8"



services:
  app:
    container_name: traveller-lite
    build: .
    environment:
      EMAIL_DEV_MODE: ${EMAIL_DEV_MODE}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_PORT: ${EMAIL_PORT}
      SUPER_ADMIN_ACCOUNT: ${SUPER_ADMIN_ACCOUNT}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}

    volumes:
      - ./instance:/app/instance
    restart: always
    network_mode: "host"
