version: "3.8"



services:
  app:
    container_name: traveller-lite
    build: .
    environment:
      EMAIL_DEV_MODE: 1
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_PORT: ${EMAIL_PORT}
      SUPER_ADMIN_ACCOUNT: ${SUPER_ADMIN_ACCOUNT}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}

    volumes:
      - ./app:/traveller-lite/app
    restart: always
    network_mode: "host"

    entrypoint: ["flask", "run", "--host=0.0.0.0", "--debug"]
