enabled = "yes"

[settings]
url_prefix = "/account-management"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
#static_url_path = "/static/account-management"
#root_path = ""
#cli_group = ""

[session]
#account_management_session = "yes"
